-----------USERS RECORD MANAGEMENT SYSTEM-----------

USING PYTHON CLASSES AND REGULAR EXPRESSION CONCEPT.

3.12 64-BIT PYTHON IDLE IS USED.

VS-CODE EDITOR.

BASIC REPRESENTATION OF USERS REGISTRATION RECORD.

CURRENTLY INCLUDED ONLY NAME, EMAIL, AND PHONE NUMBER FOR USERS DETAILS. 

YOU CAN FURTHER ADD AND UPDATE CODE AS PER YOUR REQUIREMENTS.




